name: studymate_ai_app
description: StudyMate AI App MK2 - local-first study cards, adaptive quiz, and RAG review.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  drift: ^2.17.0
  drift_sqflite: ^2.0.1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  intl: ^0.20.2
  collection: ^1.18.0
  # Firebase (optional, stubbed providers provided)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0
  drift_dev: ^2.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/sample_notes/
  generate: true
